### ISSUE TITLE
unavailable to drop image

### ISSUE THREAD

**Issue by tr00869963** [LearnCodeWeb/Dropzone-images-with-reorder#1]
I try to drag and drop image into the box but it not work.

**Comment by mianzaid** [comment]
> I try to drag and drop image into the box but it not work.

<a href="https://learncodeweb.com/demo/web-development/drag-drop-images-with-bootstrap-4-and-reorder-using-php-jquery-and-ajax/">Working Demo</a>
I just test it and it is working fine. Can you please explain more details?

**Comment by tr00869963** [comment]
thank you for answer.
I got this problem when I use chrome (version 72.0.3626.121)
when I try to drop image into the upload box it will show "ban mark".
Incognito Mode not work too.
But Firefox, IE and Edge work fine .

**Comment by tr00869963** [comment]
Problem solved after I restarted my computer.
I am sorry to have inconvenienced you.
